.TH ROCKPAPERSCISSORS 1
.SH NAME
rockpaperscissors \- play a game of rock paper scissors with a computer opponent on a server
.SH SYNOPSIS
.B make all
.B ./client
.SH DESCRIPTION
run the makefile with 
.B make all 
then, run 
.B ./client 
simultaneously in another terminal.
This would allow the client and server connection as well as the program to execute.
At the program prompt enter 1, 2, or 3 to choose rock, paper or scissors respectively.
This program can play multiple games with different users simultaneously.
.SH NOTES
User must be in working directory of the makefile. 
User must execute 
.B ./client 
in another terminal to play the game.